package com.testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obj1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String s;

	public Obj1() {
	}

	public java.lang.String getS() {
		return this.s;
	}

	public void setS(java.lang.String s) {
		this.s = s;
	}

	public Obj1(java.lang.String s) {
		this.s = s;
	}

}