package com.testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obj1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Obj1() {
    }




}