package com.testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obj1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String foo;

	public Obj1() {
	}

	public java.lang.String getFoo() {
		return this.foo;
	}

	public void setFoo(java.lang.String foo) {
		this.foo = foo;
	}

	public Obj1(java.lang.String foo) {
		this.foo = foo;
	}

}