package com.testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obj2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.testing.Obj1 obj1;

	public Obj2() {
	}

	public com.testing.Obj1 getObj1() {
		return this.obj1;
	}

	public void setObj1(com.testing.Obj1 obj1) {
		this.obj1 = obj1;
	}

	public Obj2(com.testing.Obj1 obj1) {
		this.obj1 = obj1;
	}

}