package com.testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obj3 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.testing.Obj2 obj2;

	public Obj3() {
	}

	public com.testing.Obj2 getObj2() {
		return this.obj2;
	}

	public void setObj2(com.testing.Obj2 obj2) {
		this.obj2 = obj2;
	}

	public Obj3(com.testing.Obj2 obj2) {
		this.obj2 = obj2;
	}

}