package com.testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Obj3 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.testing.Obj2 foo;

	public Obj3() {
	}

	public com.testing.Obj2 getFoo() {
		return this.foo;
	}

	public void setFoo(com.testing.Obj2 foo) {
		this.foo = foo;
	}

	public Obj3(com.testing.Obj2 foo) {
		this.foo = foo;
	}

}